apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost-ingress
  namespace: dev 
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: ghost-dev.ebaotech.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: ghost 
          servicePort: 2368
